### ISSUE TITLE
Automatic door сan be opened when it is already open.

### ISSUE THREAD

**Issue by Diffle** [TheSink/JKRF-Issue-Tracker#4]
When automatic door  is open, and you are standing in the aisle, it will open one more time and can cause visual problems (sticks out of the wall)

**Comment by TheSink** [comment]
Bug is known. We think it has something to do with the Headcrab lab's Door Release system. Do you know if it was touched at all in the server you were in?

**Comment by TheSink** [comment]
Louie rescripted the doors. They should be fine now.
